=== Verify cluster access
Check the output to ensure you are in the correct context for the cluster mentioned in the alert. If not, please change context and proceed.

.List clusters you have permission to access:
[source,role="execute"]
----
ocm list clusters
----
From the list above, find the cluster id of the cluster named in the alert. If you do not see the alerting cluster in the list above please contact: WIP

.Create a tunnel through backplane by provdiing SSH key passphrase:
[source,role="execute"]
----
ocm backplane tunnel <cluster_id> 
----

.In a new tab, login to target cluster using backplane by provdiing 2FA:
[source,role="execute"]
----
ocm backplane login <cluster_id> 
----

=== Check Alerts

.Set port-forwarding for alertmanager:
[source,role="execute"]
----
oc port-forward alertmanager-managed-ocs-alertmanager-0 9093 -n openshift-storage
----

.Check all alerts
[source,role="execute"]
----
curl http://localhost:9093/api/v1/alerts | jq '.data[] | select( .labels.alertname) | { ALERT: .labels.alertname, STATE: .status.state}'
----



=== Check OCS Ceph Cluster Health
You may directly check OCS Ceph Cluster health by using the rook-ceph toolbox.
.Step 1: Check and document ceph cluster health:
[source,role="execute"]
----
TOOLS_POD=$(oc get pods -n openshift-storage -l app=rook-ceph-tools -o name)
oc rsh -n openshift-storage $TOOLS_POD
----

.Step 2: From the rsh command prompt, run the following and capture the output.
[source,shell]
----
ceph status
ceph osd status
exit
----

If 'ceph status' is not in *HEALTH_OK*, please look at the Troubleshooting section to resolve issue.

=== Further info ===
==== OpenShift Data Foundation Dedicated Architecture ====
Red Hat OpenShift Data Foundation Dedicated (ODF Dedicated) is deployed in converged mode on OpenShift Dedicated Clusters by the OpenShift Cluster Manager add-on infrastructure.

.Related Links
- https://docs.google.com/document/d/1ISEY16OfsvEPmlJEjEwPvDvDs0KyNzgl369A-V6-GRA/edit#heading=h.mznotzn8pklp[ODF Dedicated Converged Add-on Architecure ]
- https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.6/html/planning_your_deployment/ocs-architecture_rhocs[ODF Product Architecture]

.Step 3: Check the links to identify the errors.
1) https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/4/html/troubleshooting_guide/troubleshooting-ceph-osds#common-ceph-osd-error-messages-in-the-ceph-logs_diag
2) https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/4/html/troubleshooting_guide/troubleshooting-ceph-placement-groups#inconsistent-placement-groups_diag

