
=== Notify Customer: Make changes to solve the alert

{resolution_description}

==== Delete Data


The customer may NOT delete data while in read-only mode.

If the customer wants to delete data after the cluster is in readonly mode, the resolution procedure is:

  * Raise the threshold for readonly
  * Allow the cluster to drop of out readonly
  * Instruct the customer to delete data
  * Restore the original thresholds

This is essentially the same procedure stated in https://access.redhat.com/solutions/5486241[Scaling up (adding new disks) OCS 4 fails due to cluster state being unhealthy because of lack of capacity.]

include::partial$ocs_extend_cluster.adoc[]




==== Current size < 1 TB, Expand to 4 TB

Assess ability to expand. For every 1TB of storage added, the cluster needs to have 3 nodes each with a minimum available 2 vCPUs and 8GiB memory 

The customer may increase capacity via the addon and the cluster will resolve the alert through self healing processes.
If the minimum vCPU and memory resource requirements are not met, the customer should be advised to add 3 additional worker nodes to the cluster.

==== Current size = 4TB
Add-on currently supports clusters of size upto 4TB. If customer needs additional storage, log a support case to follow exception process.

.Options for support
- Update storage cluster to size above 4TB (log support exception and contact Engineering as per escalation flow)
  
To update the storage cluster, use the below command and make sure to replace the "storage_size" placeholder with desired size value (int).
[source,role="execute"]
----
oc patch storagecluster ocs-storagecluster -p '{"spec":{"storageDeviceSets":{"count":"storage_size"}}}'
----

- If cluster is in read-only and customer wants to reclaim space by deleting PVs, follow the https://access.redhat.com/solutions/3001761[KCS] to temporarily allow delete

