
=== Notify Customer: Make changes to solve the alert

{resolution_description}

==== Delete Data
IMPORTANT: OCS CEPH CLUSTER IS NOT IN READONLY MODE. The following instructions only apply to OCS clusters that are near or full but NOT in read-only mode. Read-only mode would prevent any changes including deleting data (i.e. PVC/PV deletions)

The customer may delete data and the cluster will resolve the alert through self healing processes.

==== Current size < 1 TB, Expand to 4 TB

Assess ability to expand. For every 1TB of storage added, the cluster needs to have 3 nodes each with a minimum available 2 vCPUs and 8GiB memory 

The customer may increase capacity via the addon and the cluster will resolve the alert through self healing processes.
If the minimum vCPU and memory resource requirements are not met, the customer should be advised to add 3 additional worker nodes to the cluster.

==== Current size = 4TB
Add-on currently supports clusters of size upto 4TB. If customer needs additional storage, log a support case to follow exception process.

.Options for support
- Update storage cluster to size above 4TB (log support exception and contact Engineering as per escalation flow)
- If cluster is in read-only and customer wants to reclaim space by deleting PVs, follow the https://access.redhat.com/solutions/3001761[KCS] to temporarily allow delete
